package dev.pawan.sharemate.enums;

public enum NotificationTemplateCode {
	NEW_FRIEND_REQUEST,
	FRIEND_REQUEST_ACCEPTED,
	EXPENSE_ADDED,
	EXPENSE_UPDATED,
	EXPENSE_DELETED,
	EXPENSE_SETTLED,
	EXPENSE_REMINDER,
	FRIEND_SETTLED_UP,
	GROUP_CREATED,
	GROUP_MEMBER_ADDED,
	YOU_JOINED_GROUP,
	GROUP_DETAILS_UPDATED,
	GROUP_MEMBER_REMOVED,
}
